// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAh3fljKgpfhZ38wCidngq0vnprMdjS1w',
    appId: '1:407703990706:web:c1bd7568d7adc7c76ab4ab',
    messagingSenderId: '407703990706',
    projectId: 'e-com-8ba1f',
    authDomain: 'e-com-8ba1f.firebaseapp.com',
    storageBucket: 'e-com-8ba1f.firebasestorage.app',
    measurementId: 'G-HRGLLXWP7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIH1GPmZJwi7Q7V-Wc2hYV9QfLD4ajtzU',
    appId: '1:407703990706:android:350e70e8027076146ab4ab',
    messagingSenderId: '407703990706',
    projectId: 'e-com-8ba1f',
    storageBucket: 'e-com-8ba1f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAh3fljKgpfhZ38wCidngq0vnprMdjS1w',
    appId: '1:407703990706:web:4c610c2d616921036ab4ab',
    messagingSenderId: '407703990706',
    projectId: 'e-com-8ba1f',
    authDomain: 'e-com-8ba1f.firebaseapp.com',
    storageBucket: 'e-com-8ba1f.firebasestorage.app',
    measurementId: 'G-JKSYDKY8HP',
  );
}
